/**
 * Firestore Collections Schema for MzansiServices
 * This defines the structure and validation rules for our collections
 */

// Users Collection Schema
const usersCollectionSchema = {
  collectionName: 'users',
  documentStructure: {
    // Required fields
    name: {
      type: 'string',
      required: true,
      example: 'Thandi Mthembu'
    },
    email: {
      type: 'string', 
      required: true,
      validation: 'valid email format',
      example: 'thandi@example.com'
    },
    phone: {
      type: 'string',
      required: true,
      example: '0721234567'
    },
    location: {
      type: 'string',
      required: true,
      example: 'Soweto, Johannesburg'
    },
    
    // Auto-generated fields
    createdAt: {
      type: 'timestamp',
      required: true,
      autoGenerated: true
    },
    updatedAt: {
      type: 'timestamp', 
      required: true,
      autoGenerated: true
    },
    
    // Optional fields
    profilePicture: {
      type: 'string',
      required: false,
      description: 'URL to profile image'
    },
    isServiceProvider: {
      type: 'boolean',
      required: false,
      default: false
    }
  }
};

// Services Collection Schema  
const servicesCollectionSchema = {
  collectionName: 'services',
  documentStructure: {
    // Required fields
    title: {
      type: 'string',
      required: true,
      example: 'Professional Hair Braiding'
    },
    description: {
      type: 'string',
      required: true,
      example: 'Expert braiding services for all hair types'
    },
    price: {
      type: 'number',
      required: true,
      example: 150.00,
      validation: 'Must be positive number'
    },
    category: {
      type: 'string',
      required: true,
      enum: ['Beauty & Hair', 'Home Services', 'Automotive', 'Health & Wellness', 'Education', 'Events', 'Other'],
      example: 'Beauty & Hair'
    },
    location: {
      type: 'string',
      required: true,
      example: 'Soweto, Johannesburg'
    },
    contact: {
      type: 'string',
      required: true,
      example: '0721234567'
    },
    ownerId: {
      type: 'string',
      required: true,
      description: 'Reference to users collection document ID'
    },
    
    // Auto-generated fields
    createdAt: {
      type: 'timestamp',
      required: true,
      autoGenerated: true
    },
    updatedAt: {
      type: 'timestamp',
      required: true, 
      autoGenerated: true
    },
    
    // Optional fields
    images: {
      type: 'array',
      required: false,
      description: 'Array of image URLs'
    },
    isActive: {
      type: 'boolean',
      required: false,
      default: true
    },
    rating: {
      type: 'number',
      required: false,
      validation: 'Between 1 and 5'
    },
    reviewCount: {
      type: 'number',
      required: false,
      default: 0
    }
  }
};

module.exports = {
  usersCollectionSchema,
  servicesCollectionSchema
};
